### ISSUE TITLE
Specifying start coin and end coin ?

### ISSUE THREAD

**Issue by xCuri0** [wardbradt/peregrine#44]
title

**Comment by wardbradt** [comment]
Are you referring to arbitrage for "multiple coins on one exchange" (triangular arbitrage)?

**Comment by xCuri0** [comment]
@wardbradt when doing the bellman ford instead of looping to the source coin i want to specify to the coin to start the path and end the path with

**Comment by wardbradt** [comment]
The Bellman Ford implementation finds opportunities which are reachable from a currency. The functionality I believe you are referring to ("looping to the source coin"), which is enabled by the `loop_from_source` parameter in `bellman_ford`, was part of an experimental feature with some edge cases that could cause found opportunities to be incorrect. It has been removed from the project in the `dev` branch (the most up-to-date version of peregrine) because of this. 

For each currency `y` in an opportunity, the opportunity can be looped through starting at `y` and ending at `y`. If a found opportunity contains any currency `y`, then you can loop through the opportunity starting and ending at `y`. 

For the functionality you are requesting, where you start at some currency `x`, enter the opportunity at `y`, loop through to `y`, and end with currency `z`, there are several different ways to accomplish this, at least one of is an open research question. Feel free to research this if you want, but I currently do not have the time to implement such functionality. Also, I do not believe it aligns with the goal of this project, _finding_, not _executing_ opportunities so I am closing the issue.
